### ISSUE TITLE
Is it Rails 3 or is it Ruby 2.0 too? 

### ISSUE THREAD

**Issue by alekseyl** [instructure/canvas-lms#601]
Hi there! 
You have in ruby_version_compatibility.rb the following code:

unless CANVAS_RAILS3
  module AttributeReadWithUtf8Check
    def read_attribute(attr_name, &block)
      self.class.strip_invalid_utf8_from_attribute(attr_name, super)
    end
  end
  ActiveRecord::AttributeMethods::Read.send(:prepend, AttributeReadWithUtf8Check)
end

BUT when I use  rails 4 and ruby 1.9.3 instead of 2 I'll get undefined method `prepend' for ActiveRecord::AttributeMethods::Read:Module :( 

So I'm guessing something is wrong with condition what it filters: Rails2 or Rails2 and Rails4 :)? And what to do with code if it requires ruby 2 ?

**Comment by ccutrer** [comment]
When running Canvas with Rails 4 (which is not supported yet; we're working on it), Ruby 2.1+ is required. Ruby 2.1 is not technically supported by Canvas yet, but it's been all but rubber-stamped by QA.
