### ISSUE TITLE
NoMethodError (undefined method `unserialized_value'

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#533]
Hi Sir,

I have upgraded Canvas to the latest version today and could not access our Canvas website after the upgrade. I found the following errors in the production log.

NoMethodError (undefined method `unserialized_value' for {"api_key"=>"d4PaFtoiM0VcJKH25GvhLRQI"}:ActiveSupport::HashWithIndifferentAccess):
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/read.rb:72:in `__temp__'
  /var/canvas/app/models/plugin_setting.rb:113:in `settings_for_plugin'
  /var/canvas/lib/canvas/crocodoc.rb:3:in `config'
  /var/canvas/app/controllers/application_controller.rb:1387:in `feature_enabled?'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/helpers.rb:53:in `feature_enabled?'
  /var/canvas/app/helpers/application_helper.rb:457:in `inst_env'
  /var/canvas/app/views/layouts/_foot.html.erb:2:in `_app_views_layouts__foot_html_erb__3172357973088654191_175756200'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/template.rb:145:in `block in render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/template.rb:143:in `render'
  /var/canvas/config/initializers/i18n.rb:196:in `render_with_i18n_scope'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:237:in `render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:41:in `render_partial'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:15:in `render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/helpers/rendering_helper.rb:24:in `render'
  /var/canvas/app/views/layouts/application.html.erb:221:in `_app_views_layouts_application_html_erb___4574313191572301015_170553860'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/template.rb:145:in `block in render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/template.rb:143:in `render'
  /var/canvas/config/initializers/i18n.rb:196:in `render_with_i18n_scope'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:18:in `render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:36:in `render_template'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:17:in `render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:110:in `_render_template'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/streaming.rb:225:in `_render_template'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:103:in `render_to_body'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:88:in `render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:16:in `render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:39:in `render'
  /var/canvas/app/controllers/application_controller.rb:1578:in `render'
  /var/canvas/app/controllers/pseudonym_sessions_controller.rb:136:in `maybe_render_mobile_login'
  /var/canvas/app/controllers/pseudonym_sessions_controller.rb:120:in `new'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:602:in `block in _run__2010568564913962911__process_action__3599223235884605976__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_10580'
  /var/canvas/app/controllers/application_controller.rb:197:in `set_locale'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_10580'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:436:in `_run__2010568564913962911__process_action__3599223235884605976__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'

**Comment by simonista** [comment]
I believe these issues should all be fixed in the latest stable branch.  Let us know if you're still running into trouble!

**Comment by cvong** [comment]
After upgrading the system to 12/20 release, we have the problem again and below is the error message.

NoMethodError (undefined method `unserialized_value' for #<String:0x00000013b8e058>):
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/read.rb:84:in `__temp__'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/read.rb:46:in `type_cast_attribute'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/read.rb:127:in `read_attribute'
  /var/canvas/app/models/account.rb:379:in `settings'
  /var/canvas/app/models/account.rb:269:in `canvas_authentication?'
  /var/canvas/app/models/account.rb:935:in `delegated_authentication?'
  /var/canvas/app/controllers/application_controller.rb:402:in `delegated_authentication_url?'
  /var/canvas/app/controllers/pseudonym_sessions_controller.rb:53:in `new'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:591:in `block in _run__4460264984346363994__process_action__1325850997602181817__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_10635'
  /var/canvas/app/controllers/application_controller.rb:201:in `set_locale'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_10635'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:436:in `_run__4460264984346363994__process_action__1325850997602181817__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `block in action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  /var/canvas/lib/canvas/request_throttle.rb:58:in `block in call'
  /var/canvas/lib/canvas/request_throttle.rb:229:in `reserve_capacity'
  /var/canvas/lib/canvas/request_throttle.rb:54:in `call'
  /var/canvas/app/middleware/stats_timing.rb:8:in `block in call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
 /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /var/canvas/app/middleware/stats_timing.rb:8:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.1.8/lib/encrypted_cookie_store.rb:45:in `call'
  /var/canvas/app/middleware/sessions_timeout.rb:22:in `call'
  /var/canvas/app/middleware/load_account.rb:12:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__3622889866565063658__call__4256376035719099689__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:18:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
  /var/canvas/app/middleware/request_context_generator.rb:34:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  /var/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiler.rb:193:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/utils.rb:470:in `safe_fork'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:129:in `start'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99:in `<main>'

**Comment by ccutrer** [comment]
Are you _sure_ you don't have an old Rails 2 version of Canvas running somewhere and polluting your cache?

**Comment by cvong** [comment]
It works after I cleared the cache. Thanks.
