### ISSUE TITLE
Incoming mail fails sometimes using mail gem 2.7.0

### ISSUE THREAD

**Issue by catokolas** [instructure/canvas-lms#1423]
### Summary:
Incoming mail fails when a message has Content-Transfer-Encoding: 8bit due to 8bit characters in body part.

### Steps to reproduce:

 1. Install any release using mail gem 2.7.0
 2. Configure for processing incoming mail
 3. Reply to a mail using a mail client producing Content-Transfer-Encoding: 8bit. Other transfer encodings (7bit, base64, quoted-printable) still works as expected.

### Expected behavior:
Mail is processed successfully

### Actual behavior:
error_repors: undefined method `each' for nil:NilClass

```
undefined method `each' for nil:NilClass
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:350:in `extract_address_tag'
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:334:in `process_message'
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:291:in `block in process_mailbox'
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/directory_mailbox.rb:52:in `block in each_message'
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/directory_mailbox.rb:49:in `each'
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/directory_mailbox.rb:49:in `each_message'
/var/www/canvas/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:283:in `process_mailbox'
...
```

### Additional notes:
We're currently using release 2019-01-26.29 but this will affect all releases using mail gem 2.7.0 introduced in https://github.com/instructure/canvas-lms/commit/db262fa81fd7adbf2b3a4a7de93be4ebe48a7eb5

Investigation has found that it works again with mail gem 2.7.1, ref:
https://github.com/mikel/mail/blob/2.7.1/CHANGELOG.rdoc
